[package]
name = "rusty_pong"
version = "0.1.0"
authors = ["SilasPC <pockendahl@hotmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.32.2", features = ["bundled", "static-link"] }
gl = { path = "lib/gl" }